### ISSUE TITLE
error when starting --> TypeError: object Response can't be used in 'await' expression

### ISSUE THREAD

**Issue by ghost** [opsdroid/connector-slack#15]
```
INFO opsdroid-modules.connector.slack: Connecting to Slack
Traceback (most recent call last):
  File "/root/.opsdroid/modules/opsdroid-modules/connector/slack/__init__.py", line 46, in connect
    connection = await self.sc.rtm.start()
TypeError: object Response can't be used in 'await' expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/opsdroid", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/opsdroid/__main__.py", line 130, in main
    opsdroid.start_loop()
  File "/usr/local/lib/python3.5/dist-packages/opsdroid/core.py", line 142, in start_loop
    self.start_connector_tasks(connectors)
  File "/usr/local/lib/python3.5/dist-packages/opsdroid/core.py", line 190, in start_connector_tasks
    self.eventloop.run_until_complete(connector.connect(self))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/root/.opsdroid/modules/opsdroid-modules/connector/slack/__init__.py", line 57, in connect
    except aiohttp.errors.ClientOSError as e:
AttributeError: module 'aiohttp' has no attribute 'errors'
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by jacobtomlinson** [comment]
Thanks for raising this, not something I've seen happen before. 

Could you please include other information such as your config so I can try and reproduce? See the [issue template](https://raw.githubusercontent.com/opsdroid/opsdroid/master/docs/ISSUE_TEMPLATE.md) for more info.

**Comment by ghost** [comment]
i was using it within a ubuntu docker image.
```yaml
module-path: "/opsdroid_run_modules/"
connectors:
  - name: slack
    api-token: "REDACTED"
    bot-name: "buildbot"
    default-room: "#test_bot_channel"
    icon-emoji: ":smile:" # default ":robot_face:"
skills:
  - name: hello
```

docker version
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

python 3.5
installed on `ubuntu:xenial`
```apt install -y \
        python3-pip \
        git \
        language-pack-en \
        vim
```
Opsdroid version is latest.

**Comment by jacobtomlinson** [comment]
There is an [official opsdroid docker image](https://hub.docker.com/r/opsdroid/opsdroid/), could you try with that and see if you get the same issue?

Also could you provide your `Dockerfile`.

**Comment by ghost** [comment]
i can't upload the dockerfile(s) used (file type not allowed?) but i can paste it below.

```FROM ubuntu:xenial
MAINTAINER davidj411
EXPOSE 8080
RUN apt-get update && apt install -y \
        python3-pip \
        git \
        language-pack-en \
        vim
# note , these are my requirements. several things done in the official opsdroid dockerfile are not here.
COPY ./requirements.txt /
RUN pip3 install --upgrade pip && pip3 install -r /requirements.txt
#COPY ./configuration.yaml /etc/opsdroid/ <--this makes no difference

CMD ["python3", "-m", "opsdroid"]
```

it does work when i use this as a replacement docker file, which i will explain why next.
```
FROM opsdroid/opsdroid:latest
COPY ./configuration.yaml /etc/opsdroid/configuration.yaml
```

oddly, using `-v configuration.yaml:/etc/opsdroid/configuration.yaml:ro` in the command line resulted in the file not being read (b/c i never saw "slack" get loaded during startup).
in the container, `configuration.yaml` was seen as a folder:
```
/usr/src/app # ls -all /etc/opsdroid/
total 12
drwxr-xr-x    3 root     root          4096 Apr  4 14:17 .
drwxr-xr-x    1 root     root          4096 Apr  4 14:17 ..
drwxr-xr-x    2 root     root          4096 Apr  4 13:34 configuration.yaml
/usr/src/app # ls -all /etc/opsdroid/configuration.yaml/
total 8
drwxr-xr-x    2 root     root          4096 Apr  4 13:34 .
drwxr-xr-x    3 root     root          4096 Apr  4 14:17 ..
```

**Comment by ghost** [comment]
i had noticed that python 3.5.2 was in mine, but opsdroid was using python 3.5.4.
i installed 3.6.5 and have the same error:
```INFO opsdroid-modules.connector.slack: Connecting to Slack
Traceback (most recent call last):
  File "/root/.opsdroid/modules/opsdroid-modules/connector/slack/__init__.py", line 46, in connect
    connection = await self.sc.rtm.start()
TypeError: object Response can't be used in 'await' expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/opsdroid/__main__.py", line 140, in <module>
    init()
  File "/usr/local/lib/python3.6/site-packages/opsdroid/__main__.py", line 137, in init
    main()
  File "/usr/local/lib/python3.6/site-packages/opsdroid/__main__.py", line 130, in main
    opsdroid.start_loop()
  File "/usr/local/lib/python3.6/site-packages/opsdroid/core.py", line 142, in start_loop
    self.start_connector_tasks(connectors)
  File "/usr/local/lib/python3.6/site-packages/opsdroid/core.py", line 190, in start_connector_tasks
    self.eventloop.run_until_complete(connector.connect(self))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/root/.opsdroid/modules/opsdroid-modules/connector/slack/__init__.py", line 57, in connect
    except aiohttp.errors.ClientOSError as e:
AttributeError: module 'aiohttp' has no attribute 'errors'
```

it __must__ be in how i built my image. i can look into that later. 
there is likely no real bug here. **thanks!**

**Comment by jacobtomlinson** [comment]
No problem I will close this then. If you do get to the bottom of this and feel like a code change would make it easier to troubleshoot then feel free to add more comments to this issue.
